### ISSUE TITLE
Use SQL `offset` and `limit`

### ISSUE THREAD

**Issue by M4GNV5** [hopfenspace/MateBot#29]
Instead of querying all transaction log entries using `OFFSET` and `LIMIT` in the below SQL queries should be considered.

https://github.com/CrsiX/MateBot/blob/66c2903755291170eb7b2e4f0e652b76faa06602/mate_bot/state/transactions.py#L199-L213

**Comment by CrsiX** [comment]
Good point, thanks for reporting.
This was added in ae79517d7b516916f91197f184f4b03d1675f2e8. However, it doesn't use `OFFSET` currently. There seems to be no need to do this because `/history` shows only the most current transactions. When #31 is finished, we can go on and add a full export of all transactions for a given user.
