### ISSUE TITLE
Should collective operations be created in any chat and forwarded to the internal group instantly?

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#45]
Issue #7 offers the possibility to forward communisms to other users, but not to groups. However, we could say that a communism or payment request could be created in any chat the bot has access to, i.e. any personal chat and any group it has joined / was added to. The first management message would be sent to this private chat or group, but a second message will be sent to the internal group chat (as long as the command wasn't sent in the internal group chat).

Without being able to forward those messages to the internal group, any external would have to send the message to other internal users personally and ask them to forward it to other internal users... This would be awful.

**Comment by gammelalf** [comment]
Any command that changes users balance should send its response in the internal group. Because then the members can control / check if someone forgot something or is trying something fishy.

Meaning when I create a communism in my private chat the communism message should always appear in the internal group.

**Comment by gammelalf** [comment]
Answer yes: see #49
