### ISSUE TITLE
Every balance changing command should always reply in the internal group

### ISSUE THREAD

**Issue by gammelalf** [hopfenspace/MateBot#49]
Any command that changes users balance should send its response in the internal group. Because then the members can control / check if someone forgot something or is trying something fishy.

Also a collective in a private chat would be pointless/ annoying to forward to everyone.

**Comment by CrsiX** [comment]
But what if an external user has to use the communism/payment feature? Maybe some internals were at a party of an external user. The external user creates the communism. The others should join. So, what should the external user do? Posting to the internal group is not possible for him (however, we might want to do this automatically, that's a point of this discussion). Forwarding is therefore the currently best solution, maybe the only one.

**Comment by gammelalf** [comment]
The external should use `/communism` in his private chat. The resulting communism will then be posted in the internal group
like every balance changing command.

**Comment by CrsiX** [comment]
It is enaugh if the internal chat receives messages about what happened, i.e. already committed transactions, isn't it? This means that the bot will send a message for every performed transaction, e.g. by using `.commit(bot)` instead of the current `.commit()`. However, this argument must be optional to allow maintenance.
See a0ae67662c2b37415ad1e0bbff082a48fb53bc5b and d2b8e60cebd6c67d08adaf9b67c9c57f80503d00.
