### ISSUE TITLE
A way to forward communisms which are in the internal chat group to individual externals

### ISSUE THREAD

**Issue by gammelalf** [hopfenspace/MateBot#7]
Communisms appear in the internal chat group. This means an external which is not in this group can't join.
There should be the feature to "forward" a communism to externals to alloy them to join as well.

This would probably require some changes because the Communism object needs to keep track of all private chats with externals in which it is shown to be able to update everywhere.

**Comment by CrsiX** [comment]
It might also be a good idea to let external users create communisms in private chats with the bot. Then, there will be an additional button `FORWARD` in the inline keyboard of the replied message.

**Comment by CrsiX** [comment]
Currently (as of 088db50ab6a96c6983d5fa01233b60617f2ea4f9), the receiver of a forwarded communism does not know who forwarded the message because it's just a normal message sent by the bot. AFAIK it's not possible to add the necessary reply keyboard to forwarded messages, therefore the receiver of the message can't guess who forwarded the message without removing the full usability.

So, the only option is sending a second message along with the first message stating who forwarded the managment message to the receiver. This second message easily replies to the first message for easy setup and better understanding.

Should we do that? I would prefer it over not saying anyting. Because it allows the receiver e.g. to ask the sender something about it.

**Comment by CrsiX** [comment]
I would also implement a `forward` command. See #60.

**Comment by CrsiX** [comment]
I will close this issue. The previous comment is now placed in a new issue. See #68.
